// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARkweeyMfhq9Io50sOE_9ISq6HWYDZtRo',
    appId: '1:873712718316:web:bd5584fa0b0084693830c9',
    messagingSenderId: '873712718316',
    projectId: 'txt-invitation',
    authDomain: 'txt-invitation.firebaseapp.com',
    storageBucket: 'txt-invitation.firebasestorage.app',
    measurementId: 'G-5NE6NKL0TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZse4xBcDS0JWghqP_mdTw3NR95KJ6ebY',
    appId: '1:873712718316:android:4804d9e9f15d0e853830c9',
    messagingSenderId: '873712718316',
    projectId: 'txt-invitation',
    storageBucket: 'txt-invitation.firebasestorage.app',
  );
}
