
import 'package:flutter/material.dart';
import 'package:txt_invite/src/models/event.dart';
import 'package:txt_invite/src/services/api.dart';
import 'package:txt_invite/src/ui/widgets/create_event_steps/confirmation_step.dart';
import 'package:txt_invite/src/ui/widgets/create_event_steps/event_details_step.dart';
import 'package:txt_invite/src/ui/widgets/create_event_steps/event_settings_step.dart';
import 'package:txt_invite/src/ui/widgets/create_event_steps/guest_list_management_step.dart';
import 'package:txt_invite/src/ui/widgets/create_event_steps/invitation_customization_step.dart';
import 'package:txt_invite/src/ui/widgets/create_event_steps/template_selection_step.dart';

class CreateEventScreen extends StatefulWidget {
  const CreateEventScreen({super.key});

  @override
  State<CreateEventScreen> createState() => _CreateEventScreenState();
}

class _CreateEventScreenState extends State<CreateEventScreen> {
  final PageController _pageController = PageController();
  int _currentPage = 0;

  final List<GlobalKey<FormState>> _formKeys = List.generate(6, (_) => GlobalKey<FormState>());
  final TextEditingController _titleController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();
  DateTime? _startTime;
  DateTime? _endTime;
  String? _selectedTemplate;
  String? _selectedGuestListId;
  bool _allowComments = true;
  bool _guestListVisible = false;
  bool _rsvpRequired = true;

  @override
  void dispose() {
    _pageController.dispose();
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
  }

  Future<String> _fetchCurrentUser() async {
    final user = await Api().auth.currentUser;
    if (user == null) {
      throw Exception('User not logged in');
    }
    return user.id;
  }

  void _nextPage() {
    if (_formKeys[_currentPage].currentState != null && _formKeys[_currentPage].currentState!.validate()) {
      if (_currentPage < 5) { // Assuming 6 steps (0-5)
        _pageController.nextPage(
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeIn,
        );
        setState(() {
          _currentPage++;
        });
      }
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please complete all required fields before proceeding.')),
      );
    }
  }

  void _previousPage() {
    if (_currentPage > 0) {
      _pageController.previousPage(
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeOut,
      );
      setState(() {
        _currentPage--;
      });
    }
  }

  Future<void> _createEvent() async {
    if (_formKeys[_currentPage].currentState != null && _formKeys[_currentPage].currentState!.validate()) {
      try {
        // Simulate image generation and upload
        // In a real app, this would be replaced by actual image generation logic
        // and then uploading the generated image file.
        const String placeholderImageUrl = 'https://via.placeholder.com/150'; // Placeholder image
        // For now, we'll just use the placeholder URL directly.
        // In a real scenario, you would upload a File and get its download URL.
        // Example: final imageUrl = await Api().storage.uploadFile(imageFile, 'invitations/${newEvent.id}.png');

        final currentUserId = await _fetchCurrentUser();
        final newEvent = Event(
          id: '', // ID will be generated by Firestore
          title: _titleController.text,
          description: _descriptionController.text,
          startTime: _startTime!,
          endTime: _endTime!,
          guestListId: _selectedGuestListId!,
          invitationImageUrl: placeholderImageUrl,
          createdBy: currentUserId,
        );
        await Api().events.createEvent(newEvent);

        // Send invitation message to guests
        // final guestList = await Api().guestLists.getGuestList(_selectedGuestListId!);
        // if (guestList != null) {
        //   for (final guest in guestList.guests) {
        //     // Construct the invitation message. This can be more sophisticated.
        //     final invitationMessage = "You're invited to ${newEvent.title}! Details: ${newEvent.description}. Link: [Invitation Link Placeholder]";
        //     await Api().messaging.sendMessage(guest, invitationMessage);
        //   }
        // }

        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Event created successfully and invitations sent!')),
        );
        Navigator.of(context).pop(); // Go back to home screen
      } catch (e) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to create event: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create New Event'),
      ),
      body: Column(
              children: [
                Expanded(
                  child: PageView(
                    controller: _pageController,
                  physics: const NeverScrollableScrollPhysics(), // Disable swiping
                  onPageChanged: (index) {
                    setState(() {
                      _currentPage = index;
                    });
                  },
                  children: [
                    EventDetailsStep(
                      formKey: _formKeys[0],
                      titleController: _titleController,
                      descriptionController: _descriptionController,
                      startTime: _startTime,
                      endTime: _endTime,
                      onStartTimeChanged: (dateTime) {
                        setState(() {
                          _startTime = dateTime;
                        });
                      },
                      onEndTimeChanged: (dateTime) {
                        setState(() {
                          _endTime = dateTime;
                        });
                      },
                    ),
                    TemplateSelectionStep(
                      formKey: _formKeys[1],
                      onTemplateSelected: (template) {
                        setState(() {
                          _selectedTemplate = template;
                        });
                      },
                    ),
                    InvitationCustomizationStep(
                      formKey: _formKeys[2],
                    ),
                    GuestListManagementStep(
                      formKey: _formKeys[3],
                      onGuestListSelected: (guestListId) {
                        setState(() {
                          _selectedGuestListId = guestListId;
                        });
                      },
                    ),
                    EventSettingsStep(
                      allowComments: _allowComments,
                      guestListVisible: _guestListVisible,
                      rsvpRequired: _rsvpRequired,
                      onAllowCommentsChanged: (value) {
                        setState(() {
                          _allowComments = value;
                        });
                      },
                      onGuestListVisibleChanged: (value) {
                        setState(() {
                          _guestListVisible = value;
                        });
                      },
                      onRsvpRequiredChanged: (value) {
                        setState(() {
                          _rsvpRequired = value;
                        });
                      },
                    ),
                    ConfirmationStep(
                      title: _titleController.text,
                      description: _descriptionController.text,
                      startTime: _startTime,
                      endTime: _endTime,
                      selectedTemplate: _selectedTemplate,
                      selectedGuestListId: _selectedGuestListId,
                      allowComments: _allowComments,
                      guestListVisible: _guestListVisible,
                      rsvpRequired: _rsvpRequired,
                    ),
                  ],
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    if (_currentPage > 0)
                      ElevatedButton(
                        onPressed: _previousPage,
                        child: const Text('Previous'),
                      ),
                    if (_currentPage < 5)
                      ElevatedButton(
                        onPressed: _nextPage,
                        child: const Text('Next'),
                      ) else
                      ElevatedButton(
                        onPressed: _createEvent,
                        child: const Text('Create Event'),
                      ),
                  ],
                ),
              ),
            ],
          )
    );
  }
}
